apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-registration-test
  template:
    metadata:
      labels:
        app: user-registration-test
    spec:
      containers:
        - name: user-registration-test
          image: user-registration-test:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: user-registration-test-balancer
spec:
  selector:
    app: user-registration-test
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
