
# Ensure application is run in Vaadin 14/npm mode
logging:
  level:
    org:
      atmosphere: warn
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin:
  compatibilityMode: false
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
  pnpm: 
    enable: false

#spring:
#  security:
#    user: name
#    password